version: '3.6'

services:
  application:
    image: application
    build: .
    environment:
      APP_DATABASE_URL: mongodb://root:example@mongo:27017/my_db
      APP_PORT: 3000
    ports:
      - 9000:3000
    configs:
      - app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
configs:
  app:
    file: ./application.yml